# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone role zabbix server
      uses: actions/checkout@v2
      with:
        repository: 'iagoferreirati/role-zabbix-server'
        path: ./ansible/roles/role-zabbix-server 

    - name: Clone role mysql
      uses: actions/checkout@v2
      with:
        repository: 'iagoferreirati/ansible-role-mysql'
        path: ./ansible/roles/ansible-role-mysql

    - name: Clone role zabbix agent
      uses: actions/checkout@v2
      with:
        repository: 'iagoferreirati/role-zabbix-agent'
        path: ./ansible/roles/role-zabbix-agent  

    - name: Build AMI
      env:
        aws_access_key: ${{ secrets.aws_access_key }}
        aws_secret_key: ${{ secrets.aws_secret_key }}
      run: |
        sudo apt-get install -y packer ansible
        sudo packer build  -var "aws_access_key=${aws_access_key}" -var "aws_secret_key=${aws_secret_key}" ./packer/build.json